server:
  port: 8080

spring:
  application:
    name: fhir-terminology-service
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/fhir_terminology
    username: ${DB_USERNAME:fhir_user}
    password: ${DB_PASSWORD:fhir_password}
    driver-class-name: org.postgresql.Driver
  cache:
    type: none
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
        envers:
          audit_table_suffix: _AUDIT
          revision_field_name: REV
          revision_type_field_name: REVTYPE

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  security:
    oauth2:
      client:
        registration:
          icd:
            client-id: ${ICD_CLIENT_ID:your_icd_client_id}
            client-secret: ${ICD_CLIENT_SECRET:your_icd_client_secret}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          icd:
            token-uri: https://id.who.int/icd/oauth2/token

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_here_make_it_long_and_secure}
  expiration: 86400000 # 24 hours in milliseconds

icd:
  api:
    base-url: https://id.who.int/icd
    version: v2
    cache-ttl: 3600 # 1 hour in seconds

namaste:
  version: "1.0"
  system-uri: "http://terminology.namaste.in/CodeSystem/NAMASTE"

logging:
  level:
    com.healthcare.fhir: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG